{% set name = "LabelFusion" %}
{% set version = "1.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 88021d97ffabe111825cd8d1f68a8c4595a0ad001ffb1bff3a6017fe9df45691

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - keyring
    - numpy ==1.22.0
    - python >={{ python_min }}
    - setuptools
    - simpleitk !=2.0.*,!=2.2.1
    - twine
    - wheel
    - black

test:
  requires:
    - python {{ python_min }}
  imports:
    - LabelFusion

about:
  home: https://github.com/FETS-AI/LabelFusion
  summary: Label fusion strategies for multi-class labels.
  license: LicenseRef-CBICA
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
