{% set name = "LabelFusion" %}
{% set version = "1.0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/LabelFusion-{{ version }}.tar.gz
  sha256: 4daf4e66be26e7e7b4908ae8cc049b94383b9bb6255c609bdc7ba082b3cb3a4c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - keyring
    - numpy ==1.22.0
    - python >={{ python_min }}
    - setuptools
    - simpleitk !=2.0.*,!=2.2.1
    - twine
    - wheel
    - black

test:
  requires:
    - python {{ python_min }}
  imports:
    - LabelFusion

about:
  home: https://github.com/FETS-AI/LabelFusion
  summary: Label fusion strategies for multi-class labels.
  license: LicenseRef-CBICA
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
