{% set name = "LabelFusion" %}
{% set version = "1.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LabelFusion-{{ version }}.tar.gz
  sha256: 180683c345d293d3c4de50b12466cc1a3cd2fb5ef46ca43728ea814015ec6250

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - keyring
    - numpy ==1.19.4
    - python >=3.6
    - setuptools
    - simpleitk ==2.0.2
    - twine
    - wheel

test:
  imports:
    - LabelFusion

about:
  home: https://github.com/FETS-AI/LabelFusion
  summary: Label fusion strategies for multi-class labels.
  license: LicenseRef-CBICA
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
